server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: eureka1
