server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒)
    enable-self-preservation: false #设置为false表示关闭保护模式
  instance:
    hostname: eureka1
