server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url: {defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka}
turbine:
  app-config: MYCLOUD-PRODUCT,MYCLOUD-USER
  cluster-name-expression: new String("default")